// Demo seed data for the marketplace
export const demoListings = [
  {
    crop: 'Rice (Basmati)',
    grade: 'Grade A',
    quantity: 5000,
    unit: 'kg',
    pricePerUnit: 2750,
    mandi: 'Karnal Mandi, Haryana',
    packaging: '50kg bags',
    harvestDate: '2025-10-10',
    description: 'Premium quality Basmati rice, freshly harvested. Minimum order 500kg.',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c'],
    certification: 'Organic Certified',
  },
  {
    crop: 'Wheat',
    grade: 'Grade A',
    quantity: 10000,
    unit: 'kg',
    pricePerUnit: 2100,
    mandi: 'Azadpur Mandi, Delhi',
    packaging: '40kg bags',
    harvestDate: '2025-10-05',
    description: 'High quality wheat suitable for flour milling. Bulk orders welcome.',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b'],
  },
  {
    crop: 'Tomato',
    grade: 'Grade B',
    quantity: 2000,
    unit: 'kg',
    pricePerUnit: 16,
    mandi: 'Koyambedu Market, Tamil Nadu',
    packaging: 'Crates (20kg each)',
    harvestDate: '2025-10-18',
    description: 'Fresh tomatoes, ideal for wholesale. Quick delivery available.',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea'],
  },
  {
    crop: 'Onion',
    grade: 'Grade A',
    quantity: 8000,
    unit: 'kg',
    pricePerUnit: 20,
    mandi: 'Lasalgaon Mandi, Maharashtra',
    packaging: '25kg mesh bags',
    harvestDate: '2025-10-08',
    description: 'Premium quality onions. Storage facility available for bulk buyers.',
    images: ['https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb'],
  },
  {
    crop: 'Potato',
    grade: 'Grade A',
    quantity: 3000,
    unit: 'kg',
    pricePerUnit: 11,
    mandi: 'Agra Mandi, Uttar Pradesh',
    packaging: '50kg jute bags',
    harvestDate: '2025-10-12',
    description: 'Good quality potatoes for retail and wholesale. Negotiable prices for large orders.',
    images: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655'],
  },
  {
    crop: 'Grapes',
    grade: 'Premium',
    quantity: 1500,
    unit: 'kg',
    pricePerUnit: 45,
    mandi: 'Nashik Mandi, Maharashtra',
    packaging: '5kg boxes',
    harvestDate: '2025-10-17',
    description: 'Premium export quality grapes. Perfect for retail chains and exporters.',
    images: ['https://images.unsplash.com/photo-1601275618229-9c72d0558ab2'],
    certification: 'Export Quality',
  },
];
